### PR TITLE
release: abi enum, docker updates, code cleanup

### PR DESCRIPTION
**Pull request by mitche50**
Included in release:
- ABI Enum addition
- pytest-cov for code coverage
- remove commented code
- add `__init__.py` files
- update docker configurations for new `docker-compose` setup
- abstract integration tests from unit tests for quicker testing
- GQL removal of async and adding retries
- remove testing folders from codecov

### CODE REVIEW

**Review by Darruma — DISMISSED** [review]

**Review by SHAKOTN — APPROVED** [review]
Changes look OK. Mostly my refactorings and @Darruma added new Enum

**Comment by Darruma** [comment]
Lgtm

**Review by btcookies — APPROVED** [review]
LGTM

**Review by Pojielp — COMMENTED** [review]
a09a28937ef4e6a632a5d99c26871e8ef5e2d34a

**Review by Pojielp — COMMENTED** [review]
d0aa45a48fd4bd69e57e47f3bf4614dd4902a4ec

**Review by Pojielp — COMMENTED** [review]
bf1b841795d869bf6320fb6314123d3ea0271c5b

**Review by Pojielp — COMMENTED** [review]
bf1b841795d869bf6320fb6314123d3ea0271c5b

**Pull request merged**
